### ISSUE TITLE
drupal 7 ubercart update recurring fee billing info but next charge date doesn't change

### ISSUE THREAD

**Issue by fineartist99** [validoll/yml_tools#2]
So I was doing some testing to make sure the subscription site that I created would be all good but I did this test and I cannot seem to get the paid subscription site to function as a normal subscription site should.

I created a test account that purchased the subscription from my site. The subscription went through just fine. The test subscription that I created was a 1 day subscription for $1. So all was well, I was granted the role I was supposed to have been granted. So then, before my renewal was going to happen in 24 hours I updated my billing info to an expired cc. I let the system run the course of billing it and the recurring fee did not process and my role was removed. All is well, the site functions as it should. But now, me as a test user account sings in a day or 2 later to update my billing info so I can regain my role/subscription and the site allows me to update my cc and billing info here user/225/recurring-fees - I allowed people to view and update their recurring fees so this is visible to them.

Here's where my problem arises. I notice the Next charge was 04/25/2015 - 02:08 before I updated my cc and billing info and after I hit update the Next charge date didn't change. So the site does not charge the new cc info and on this test account my recurring fee never processes because it is now 4/27/2015 - 02:57

I was thinking I could create a rule to change the Next charge date and time but I see no possible options in rules to make that update happen.

Please advise and thank you in advance for any help.

**Comment by validoll** [comment]
What?

**Comment by fineartist99** [comment]
Instead of just saying what, can you elaborate as to what exactly you don't understand with my problem?  

I have created a subscription site with drupal and ubercart and recurring fee.  I have a $1/day recurring fee product.  When an end user buys the product they are granted access to more features of the site.

My problem is this, I bought the product and the site did what it was supposed to do.  I was granted the role and all was fine.  Now, before a day passed, before the recurring fee ran I updated my credit card information to an expired credit card so - on purpose - the recurring fee would fail and my role would get removed - which happened.  Now, I let 2 days pass then I went into the site and updated my credit card info to a valid one but when I hit save the next bill date still said 4/25/15 instead of the day it was, which was 4/27/15 so I am in need of some rule that I can create within the site that would, upon updating billing information, after recurring fee failed, the next bill date would get updated to the time of the event of updating the billing info.

**Comment by validoll** [comment]
What's the problem with my module yml_tools?

**Comment by fineartist99** [comment]
I don't use yml_tools nor do I know how to.  I did a quick look online and checked it out.  Why did you mention yml_tools?  I'm using Drupal 7 and the module UC Recurring Payments and Subscriptions Version: 7.x-2.0-alpha3

**Comment by validoll** [comment]
This is issue queue for yml_tools module.
Please create issue on https://www.drupal.org/project/uc_recurring

**Comment by fineartist99** [comment]
OH, I see what you're saying.  Sorry - I didn't notice. I never posted anything to github b4
